### ISSUE TITLE
model":"chuangmi.remote.v2 and error  Error: check power/network connection. Error: <class 'AttributeError'>

### ISSUE THREAD

**Issue by Ki-8** [Whilser/Xiaomi-Universal-IR-Remote-Controller-Domoticz-plugin#2]
Hello,
Could You Help me Please?
Finally i made some progress and got chuangmi.remote.v2 partly working,
I could get status of device, also could learn and create IR buttons, 
But I cant send that code, while im receiving Error: (Xiaomi Pultas) Xiaomi Pultas with ID 124910007 is not responding, check power/network connection. Error: <class 'AttributeError'>
Any ideas whats wrong?
Few more mentions, I only got some responce from device only after I manually added token, IP and device ID to Chuangmi/plugin.py script
I cant discover device with line "mirobot discover Only with command line "mirobo discover --handshake 1

Domoticz is latest stable version
Python 3.6.8
Also have other miio devices which work fine, like vacuum, mi flora, hub, and yeelights.

Best Regards,
Linas

EDIT:
Also this may help
mirobo --ip 192.168.0.126 --token xxxxxxxxxxxxxxxxxxxxxxxx raw_command miIO.ir_play '{"freq": 38400, "code": "base64..."}'
ERROR:miio.vacuum_cli:Unable to read the stored msgid: [Errno 2] No such file or directory: '/tmp/python-mirobo.seq'
Sending cmd miIO.ir_play with params {'freq': 38400, 'code': 'base64...'}
['ok']

EDIT2:
So Yes, if i manually push code which i got with this script, i get success.
Example:
mirobo --ip 192.168.0.126 --token f4xxxxxxxxxxxxxxxxxxxxxxxxxxx raw_command miIO.ir_play '{"freq": 38400, "code":"mc0m8wlkxm8ymEsmk0ADIAcwAymMzmIBBTUBCQHEAgcCigF8AbsAfwP+mMynIEngUeAf4KHhY+FiYFHgH+Av4B/gkQBhQLMBZqAj4LngMeB34Hfg4cI3cwgA=="}'
Sending cmd miIO.ir_play with params {'freq': 38400, 'code': 'mc0m8wlkxm8ymEsmk0ADIAcwAymMzmIBBTUBCQHEAgcCigF8AbsAfwP+mMynIEngUeAf4KHhY+FiYFHgH+Av4B/gkQBhQLMBZqAj4LngMeB34Hfg4cI3cwgA=='}
['ok']

So what is wrong? why script ends up reporting that it failed sooner than it actually could connect and push that code?
Should I edit Timeouts or delays in script?

**Comment by Whilser** [comment]
Hello, I think the issue is in the new revision of the Chuangmi IR. I think it's not fully support now, it does not send tokens with handshake packet . Try my last commit. I changed the setup page, so you can enter the IP address and token directly. 

There may be issue with attributes caused by incorrect edit plugin code. No need to edit timeouts. 

I tested on python 3.5, everything works correctly for me.

**Comment by Ki-8** [comment]
Hello,
Yes, even commands to send the code looks difrent?
Just did regular virtual dummy switches with hand made scripts. Works for basic tasks.
Your plugin still usefull to get IR codes :)

Thank You for Your hard work Whilser.

Best Regards,
L

**Comment by Whilser** [comment]
No, codes is the same. Dummy switches are actually not a very good solution. Also check that you install miio in a virtual env  python  as described in the readme.

**Comment by Ki-8** [comment]
Everything installed as per instruction and triple checked.
Only thing that bothers me that I receive Error faster that you could actually send command, and after error I think nothing happens.

**Comment by Ki-8** [comment]
I will check future updates, to know if something has changed
