### ISSUE TITLE
discovery mode didn't found any IR device.

### ISSUE THREAD

**Issue by kdsystem** [Whilser/Xiaomi-Universal-IR-Remote-Controller-Domoticz-plugin#3]
so plugin didn't found any IR device.
i know it's IP address but i didn't know the token.
Could you please help me to find this token?

**Comment by Whilser** [comment]
https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md

**Comment by kdsystem** [comment]
great, thank's
all is working now.
