### ISSUE TITLE
Полное удаление устройств

### ISSUE THREAD

**Issue by ReWiG** [Whilser/Xiaomi-Universal-IR-Remote-Controller-Domoticz-plugin#5]
Привет, имеется ли хоть какая-либо возможность полностью удалить ненужные созданные устройства из системы? Сейчас, как я понял, возможно только деактивировать их.

**Comment by Whilser** [comment]
Привет. Теоретически можно, в папке с плагином лежит json файл с конфигурацией, его можно править вручную. Но лучше деактивировать т. к. некорректно выполненные правки отрицательно скажутся на стабильности работы плагина. Можно просто удалить этот файл, перезапустить плагин и создать все устройства по-новой.

**Comment by ReWiG** [comment]
Спасибо, пока ждал ответа, уже сам выполнил данную работу, всё четко, единственное замечание что файл надо редактировать под sudo
