### ISSUE TITLE
Python 3.5.x 

### ISSUE THREAD

**Issue by Loook11** [Whilser/Xiaomi-Universal-IR-Remote-Controller-Domoticz-plugin#7]
minimal Python version 3.6 ? or 3.5.x ?
Collecting python-miio
  Using cached https://files.pythonhosted.org/packages/ef/b1/2d4c7b9092744049f21ff0b02e9d01720db9367006bbff68077cc1e6b8b7/python_miio-0.4.8-py3-none-any.whl
ERROR: Package 'python-miio' requires a different Python: 3.5.3 not in '>=3.6'

**Comment by Whilser** [comment]
Use pip3 install python-miio==0.4.6
